In [65]:
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn import metrics

### 데이터 읽어온 후 RandomForest로 반응자 예측하기
- 예측한 반응자는 response_people에 저장

In [46]:
train_x = pd.read_csv('../trnx.csv', header=None)
train_y = pd.read_csv('../trny.csv', header=None)
train_dol = pd.read_csv('../trndol.csv', header=None)
test_x = pd.read_csv('../tstx.csv', header=None)

In [47]:
train_x

0        1   2   3   4    5        6         7         8     9   \
0     -0.92575 -0.34309   1  -1  -1  0.0 -0.77778 -0.333330  0.189970 -0.50   
1     -0.92575 -0.34309   1  -1  -1 -0.8 -0.77778 -0.333330 -1.000000 -0.75   
2     -0.90100 -0.46830   1  -1  -1 -0.7 -0.55556 -0.057191 -0.349560 -0.50   
3     -0.86940 -0.57487  -1   1  -1 -0.9 -0.77778 -0.333330 -0.719870 -0.75   
4     -0.93839 -0.25525   1  -1  -1 -0.4 -0.55556 -0.057191 -0.030911 -0.50   
...        ...      ...  ..  ..  ..  ...      ...       ...       ...   ...   
50761 -0.15587 -0.94965  -1  -1  -1 -0.9 -1.00000 -1.000000 -1.000000 -1.00   
50762 -0.51448 -0.88889  -1  -1  -1 -0.9 -1.00000 -1.000000 -1.000000 -1.00   
50763 -0.34597 -0.92528  -1  -1  -1 -0.6 -1.00000 -1.000000 -1.000000 -1.00   
50764 -0.56187 -0.87401  -1  -1  -1 -0.9 -1.00000 -1.000000 -1.000000 -1.00   
50765 -0.56293 -0.87365  -1  -1  -1 -0.8 -1.00000 -1.000000 -1.000000 -1.00   

            10       11       12        13       14  
0      0.66667 -0.76822 -0.90476 -0.001805 -0.83019  
1     -0.66667 -0.86023 -0.80952 -0.001805 -1.00000  
2     -0.66667 -0.90117 -0.90476 -0.001805 -0.96226  
3     -0.83333 -1.00000 -1.00000 -0.001805 -0.98113  
4     -0.33333 -0.77900 -0.80952 -0.001805 -0.90566  
...        ...      ...      ...       ...      ...  
50761 -0.83333 -0.93011 -0.90476 -0.335740 -1.00000  
50762 -0.83333 -0.93011 -0.90476 -0.001805 -1.00000  
50763 -0.50000 -0.75791 -0.71429 -0.335740 -0.98113  
50764 -0.83333 -0.93011 -0.90476 -0.335740 -1.00000  
50765 -0.66667 -0.90117 -0.90476 -0.001805 -0.98113  

[50766 rows x 15 columns]

In [48]:
train_y

0
0      1
1      1
2      1
3      1
4      1
...   ..
50761 -1
50762 -1
50763 -1
50764 -1
50765 -1

[50766 rows x 1 columns]

In [49]:
train_dol

0
0       9
1      67
2      10
3      36
4      35
...    ..
50761   0
50762   0
50763   0
50764   0
50765   0

[50766 rows x 1 columns]

In [55]:
test_x

0        1   2   3   4    5        6         7        8     9   \
0     -0.713010 -0.79765  -1  -1   1 -0.8 -1.00000 -1.000000 -1.00000 -1.00   
1     -0.191150 -0.94596  -1  -1  -1 -0.7 -1.00000 -1.000000 -1.00000 -1.00   
2     -0.653500 -0.83488  -1  -1  -1 -0.7 -1.00000 -1.000000 -1.00000 -1.00   
3     -0.901000 -0.46830   1  -1  -1 -0.7 -0.55556 -0.057191 -0.71987 -0.75   
4     -0.864140 -0.58888  -1   1  -1 -0.9 -0.77778 -0.333330 -0.71987 -0.75   
...         ...      ...  ..  ..  ..  ...      ...       ...      ...   ...   
50761 -0.289100 -0.93387  -1  -1  -1 -0.9 -1.00000 -1.000000 -1.00000 -1.00   
50762 -0.713530 -0.79726  -1  -1   1 -0.8 -1.00000 -1.000000 -1.00000 -1.00   
50763 -0.093734 -0.95549  -1  -1  -1 -0.8 -1.00000 -1.000000 -1.00000 -1.00   
50764  0.064244 -0.96738  -1  -1  -1 -0.7 -1.00000 -1.000000 -1.00000 -1.00   
50765 -0.093207 -0.95554  -1  -1  -1 -0.9 -1.00000 -1.000000 -1.00000 -1.00   

            10       11       12        13       14  
0     -0.66667 -0.90117 -0.90476 -0.001805 -0.98113  
1     -0.66667 -0.82882 -0.80952 -0.669680 -0.98113  
2     -0.50000 -1.00000 -1.00000 -0.001805 -0.94340  
3     -0.66667 -0.86023 -0.80952 -0.502710 -0.98113  
4     -0.83333 -1.00000 -1.00000 -0.001805 -0.98113  
...        ...      ...      ...       ...      ...  
50761 -0.83333 -1.00000 -1.00000 -0.602890 -0.98113  
50762 -0.66667 -0.90117 -0.90476 -0.669680 -0.98113  
50763 -0.66667 -1.00000 -1.00000 -0.602890 -0.96226  
50764 -0.50000 -0.87895 -0.90476 -0.335740 -0.96226  
50765 -0.83333 -1.00000 -1.00000 -0.001805 -0.96226  

[50766 rows x 15 columns]

In [57]:
trnx = np.array(train_x)
trny = np.array(train_y)
trndol = np.array(train_dol)
tstx = np.array(test_x)

In [58]:
trnx

array([[-0.92575  , -0.34309  ,  1.       , ..., -0.90476  , -0.0018051,
        -0.83019  ],
       [-0.92575  , -0.34309  ,  1.       , ..., -0.80952  , -0.0018051,
        -1.       ],
       [-0.901    , -0.4683   ,  1.       , ..., -0.90476  , -0.0018051,
        -0.96226  ],
       ...,
       [-0.34597  , -0.92528  , -1.       , ..., -0.71429  , -0.33574  ,
        -0.98113  ],
       [-0.56187  , -0.87401  , -1.       , ..., -0.90476  , -0.33574  ,
        -1.       ],
       [-0.56293  , -0.87365  , -1.       , ..., -0.90476  , -0.0018051,
        -0.98113  ]])

In [59]:
trny

array([[ 1],
       [ 1],
       [ 1],
       ...,
       [-1],
       [-1],
       [-1]], dtype=int64)

In [60]:
trndol

array([[ 9],
       [67],
       [10],
       ...,
       [ 0],
       [ 0],
       [ 0]], dtype=int64)

In [111]:
rf_model = RandomForestClassifier(max_depth=15, n_estimators=100, random_state=0)

In [113]:
rf_model.fit(X=trnx[:, :], y=trny[:, 0])

RandomForestClassifier(max_depth=15, random_state=0)

In [115]:
rf_pred = rf_model.predict(X=tstx)

In [116]:
rf_pred

array([-1, -1, -1, ..., -1, -1, -1], dtype=int64)

In [117]:
rf_pred_1 = np.where(rf_pred == 1)
rf_pred_1

(array([    3,    17,    33, ..., 50742, 50743, 50750], dtype=int64),)

In [118]:
len(rf_pred_1[0])

4458

In [119]:
response_people = rf_pred_1[0]
response_people

array([    3,    17,    33, ..., 50742, 50743, 50750], dtype=int64)

### 데이터 읽어온 후 Regression으로 반응 금액 예측하기

In [120]:
from sklearn.linear_model import LinearRegression

In [134]:
reg_model = LinearRegression()
reg_model.fit(X=trnx[:,:], y=trndol[:,0])

LinearRegression()

In [140]:
reg_pred = reg_model.predict(X=tstx)
reg_pred

array([ 2.72935879,  6.4826522 ,  4.47508969, ...,  3.32615718,
       -0.49316573,  0.75266341])

In [138]:
reg_pred_1 = np.where(reg_pred == 0)
reg_pred_1

(array([], dtype=int64),)